INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (1, 'GKUD "Alat-SWISSLION"', 'gkudalat@teol.net', 89101);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (2, 'KUD "Hercegovac"', 'maja.her@gmail.com', 89101);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (3, 'ANIP "V. Maslesa"', 'ckudm.veselin.maslesa@gmail.com', 78000);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (4, 'KUD "Cajevac"', 'kudcajevac@gmail.com', 78000);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (5, 'KUD "Mladost"', 'cvoromilan@gmial.com', 71420);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (6, 'KUDM "Bosiljak"', 'kudmbosiljak@gmail.com', 74400);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (7, 'KUD "Piskavica" Piskavica', 'mirko.a@teol.net', 78000);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (8, 'ANIP "Mladost" Zaluzani', 'kud_mladost@blic.net', 78000);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (9, 'KUD "Kolovit"', 'kolovit@gmail.com', 78400);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (10, 'KUD "P. I Karadjordjevic Mrkonjic"', 'kudpetarikaradordevicmrkonjic@gmail.com', 70260);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (11, 'KUD "Zagorje" ', 'kudzagorjekalinovik@gmial.com', 71230);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (12, 'CKUD "Lepa Radic"', 'ckud.leparadic@yahoo.com', 78400);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (13, 'SKUD "Dr. Mladen Stojanovic', 'n.aleksic1962@gmail.com', 79101);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (14, 'KUD "Doboj"', 'gkuddoboj@gmail.com', 74000);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (15, 'KUD "Una"', 'sinisa_jovanic@hotmail.com', 79220);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (16, 'KUD "Milan Egic" Brezicani', 'kudmilanegic@gmail.com', 79101);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (17, 'SKUD "Derventa"', 'skudderventa@yahoo.com', 74400);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (18, 'KUD "Joco Savic" Ilicka', 'kudilickal@gmail.com', 76101);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (19, 'KUD "Milos Kupres" Kozuhe', 'djole69kozuhe@gmail.com', 74000);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (20, 'KUD "Sveti Sava"', 'svetisavabl@gmail.com', 78000);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (21, 'KUD "Pletenica" Bijeljina', 'kudpletenicabn@gmail.com', 76300);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (22, 'KUD "Zoran Tomusilovic" Dugo Polje', 'goranp72@gmail.com', 74480);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (23, 'KUD "Krnjin" Grabovica', 'kudkrnjingrabovica2015@gmail.com', 74000);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (24, 'KUD "Dusan Stankoivc" Ceceva', 'natasamastilovic1@gmail.com', 74270);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (25, 'RKUD "Pelagic"', 'arezina_aleksandra@yahoo.com', 78000);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (26, 'OKUD "Petar Kocic" Nova Topola', 'okud.petarkocic@yahoo.com', 78400);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (27, 'KUD "Slavija"', 'kudslavija@hotmail.com', 71123);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (28, 'KUD "Most" Bratunac', 'mostbratunac@gmail.com', 75420);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (29, 'KUD "Potkozarje"', 'kud.potkozarje@hotmail.com', 78000);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (30, 'KUD "Djerdan" Laktasi', 'kud.djerdan@gmail.com', 78250);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (31, 'KUD "Vez" Teslic', 'drinicmalicd@gmail.com', 74270);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (32, 'KUD "Milos Dujic Miso" Celinac', 'milosdujicmiso@gmail.com', 78240);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (33, 'GKUD "Pronija"', 'ljsibincic@gmail.com', 78430);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (34, 'KUD "Prota Matija Popovic" Milici', 'mlalovic83@gmail.com', 75446);
INSERT INTO KUD(IDKUD, NAZKUD, ADRKUD, GRAD_POSTBRG) VALUES (35, 'KUD "Osjecani"', 'kud.osjecani@hotmail.com', 74000);