INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (1, 'Srpska vojnicka nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (2, 'Srpska narodna nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (3, 'Sumadijska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (4, 'Sumadijska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (5, 'Opsta srpska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (6, 'Opsta srpska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (7, 'Moravska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (8, 'Moravska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (9, 'Zlatiborska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (10, 'Zlatiborska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (11, 'Vojvodjanska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (12, 'Vojvodjanska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (13, 'Svadbarska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (14, 'Svadbarska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (15, 'Timočka nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (16, 'Timočka nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (17, 'Vranjanska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (18, 'Vranjanska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (19, 'Sarajevska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (20, 'Sarajevska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (21, 'Kosovska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (22, 'Kosovska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (23, 'Sremska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (24, 'Sremska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (25, 'Raška nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (26, 'Raška nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (27, 'Banatska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (28, 'Banatska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (29, 'Bokeljska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (30, 'Bokeljska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (31, 'Crnogorska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (32, 'Crnogorska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (33, 'Pčinjska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (34, 'Pčinjska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (35, 'Guslarska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (36, 'Guslarska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (37, 'Mačvanska nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (38, 'Mačvanska nosnja', 'Zenska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (39, 'Timocka nosnja', 'Muska');
INSERT INTO NOSNJA (IDN, NAZN, TIPN) VALUES (40, 'Timocka nosnja', 'Zenska');
