INSERT INTO PROBA (IDP, TRP, VRPOCP) VALUES (1, 2, 'PON 18:00');
INSERT INTO PROBA (IDP, TRP, VRPOCP) VALUES (2, 2, 'PON 20:00');
INSERT INTO PROBA (IDP, TRP, VRPOCP) VALUES (3, 2, 'UTO 18:00');
INSERT INTO PROBA (IDP, TRP, VRPOCP) VALUES (4, 2, 'UTO 20:00');
INSERT INTO PROBA (IDP, TRP, VRPOCP) VALUES (5, 2, 'SRE 18:00');
INSERT INTO PROBA (IDP, TRP, VRPOCP) VALUES (6, 2, 'SRE 20:00');
INSERT INTO PROBA (IDP, TRP, VRPOCP) VALUES (7, 2, 'CET 18:00');
INSERT INTO PROBA (IDP, TRP, VRPOCP) VALUES (8, 2, 'CET 20:00');
INSERT INTO PROBA (IDP, TRP, VRPOCP) VALUES (9, 2, 'PET 18:00');
INSERT INTO PROBA (IDP, TRP, VRPOCP) VALUES (10, 2, 'PET 20:00');

