INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (1, 'Izvodjacki ansambl Alat-Swislion', 'Izvodjacka', 1);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (2, 'Pripremni ansambl Alat-Swislion', 'Pripremna', 1);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (3, 'Izvodjacki ansambl Hercegovac', 'Izvodjacka', 2);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (4, 'Pripremni ansambl Hercegovac', 'Pripremna', 2);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (5, 'Izvodjacki ansambl V. Maslesa', 'Izvodjacka', 3);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (6, 'Pripremni ansambl V. Maslesa', 'Pripremna', 3);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (7, 'Izvodjacki ansambl Cajevac', 'Izvodjacka', 4);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (8, 'Pripremni ansambl Cajevac', 'Pripremna', 4);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (9, 'Izvodjacki ansambl Mladost', 'Izvodjacka', 5);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (10, 'Pripremni ansambl Mladost', 'Pripremna', 5);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (11, 'Izvodjacki ansambl Bosiljak', 'Izvodjacka', 6);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (12, 'Pripremni ansambl Bosiljak', 'Pripremna', 6);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (13, 'Izvodjacki ansambl Piskavica', 'Izvodjacka', 7);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (14, 'Pripremni ansambl Piskavica', 'Pripremna', 7);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (15, 'Izvodjacki ansambl Mladost', 'Izvodjacka', 8);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (16, 'Pripremni ansambl Mladost', 'Pripremna', 8);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (17, 'Izvodjacki ansambl Kolovit', 'Izvodjacka', 9);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (18, 'Pripremni ansambl Kolovit', 'Pripremna', 9);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (19, 'Izvodjacki ansambl P. I Karadjordjevic Mrkonjic', 'Izvodjacka', 10);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (20, 'Pripremni ansambl P. I Karadjordjevic Mrkonjic', 'Pripremna', 10);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (21, 'Izvodjacki ansambl Zagorje', 'Izvodjacka', 11);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (22, 'Pripremni ansambl Zagorje', 'Pripremna', 11);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (23, 'Izvodjacki ansambl Lepa Radic', 'Izvodjacka', 12);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (24, 'Pripremni ansambl Lepa Radic', 'Pripremna', 12);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (25, 'Izvodjacki ansambl Dr. Mladen Stojanovic', 'Izvodjacka', 13);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (26, 'Pripremni ansambl Dr. Mladen Stojanovic', 'Pripremna', 13);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (27, 'Izvodjacki ansambl Doboj', 'Izvodjacka', 14);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (28, 'Pripremni ansambl Doboj', 'Pripremna', 14);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (29, 'Izvodjacki ansambl Una', 'Izvodjacka', 15);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (30, 'Pripremni ansambl Una', 'Pripremna', 15);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (31, 'Izvodjacki ansambl Milan Egic', 'Izvodjacka', 16);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (32, 'Pripremni ansambl Milan Egic', 'Pripremna', 16);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (33, 'Izvodjacki ansambl Derventa', 'Izvodjacka', 17);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (34, 'Pripremni ansambl Derventa', 'Pripremna', 17);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (35, 'Izvodjacki ansambl Joco Savic', 'Izvodjacka', 18);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (36, 'Pripremni ansambl Joco Savic', 'Pripremna', 18);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (37, 'Izvodjacki ansambl Milos Kupres', 'Izvodjacka', 19);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (38, 'Pocetna grupa Milos Kupres'. 'Pocetna', 19);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (39, 'Izvodjacki ansambl Sveti Sava', 'Izvodjacka', 20);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (40, 'Pripremni ansambl Sveti Sava', 'Pripremna', 20);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (41, 'Rekreativna grupa Sveti Sava', 'Rekreativna', 20);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (42, 'Skolica folklora Sveti Sava', 'Skolica folklora', 20);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (43, 'Pocetna grupa Sveti Sava', 'Pocetna', 20);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (44, 'Izvodjacki ansambl Pletenica', 'Izvodjacka', 21);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (45, 'Rekreativna grupa Pletenica', 'Rekreativna', 21);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (46, 'Dečiji ansambl Pletenica', 'Skolica folklora', 21);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (47, 'Izvodjacki ansambl Zoran Tomusilovic', 'Izvodjacka', 22);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (48, 'Pripremni ansambl Zoran Tomusilovic', 'Pripremna', 22);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (49, 'Rekreativna grupa Zoran Tomusilovic', 'Rekreativna', 22);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (50, 'Skolica folklora Zoran Tomusilovic', 'Skolica folklora', 22);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (51, 'Izvodjacki ansambl Krnjin', 'Izvodjacka', 23);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (52, 'Pripremni ansambl Krnjin', 'Pripremna', 23);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (53, 'Rekreativna grupa Krnjin', 'Rekreativna', 23);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (54, 'Skolica folklora Krnjin', 'Skolica folklora', 23);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (55, 'Izvodjacki ansambl Dusan Stankovic', 'Izvodjacka', 24);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (56, 'Pripremni ansambl Dusan Stankovic', 'Pripremna', 24);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (57, 'Rekreativna grupa Dusan Stankovic', 'Rekreativna', 24);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (58, 'Skolica folklora Dusan Stankovic', 'Skolica folklora', 24);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (59, 'Izvodjacki ansambl Pelagic', 'Izvodjacka', 25);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (60, 'Pripremni ansambl Pelagic', 'Pripremna', 25);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (61, 'Rekreativna grupa Pelagic', 'Rekreativna', 25);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (62, 'Dečiji ansambl Pelagic', 'Pocetna', 25);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (63, 'Izvodjacki ansambl Petar Kocic Nova Topola', 'Izvodjacka', 26);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (64, 'Pripremni ansambl Petar Kocic Nova Topola', 'Pripremna', 26);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (65, 'Rekreativna grupa Petar Kocic Nova Topola', 'Rekreativna', 26);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (66, 'Skolica folklora Petar Kocic Nova Topola', 'Skolica folklora', 26);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (67, 'Izvodjacki ansambl Slavija', 'Izvodjacka', 27);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (68, 'Pripremni ansambl Slavija', 'Pripremna', 27);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (69, 'Rekreativna grupa Slavija', 'Rekreativna', 27);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (70, 'Dečiji ansambl Slavija', 'Pocetna', 27);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (71, 'Izvodjacki ansambl Most Bratunac', 'Izvodjacka', 28);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (72, 'Pripremni ansambl Most Bratunac', 'Pripremna', 28);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (73, 'Rekreativna grupa Most Bratunac', 'Rekreativna', 28);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (74, 'Skolica folklora Most Bratunac', 'Skolica folklora', 28);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (75, 'Izvodjacki ansambl Potkozarje', 'Izvodjacka', 29);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (76, 'Pripremni ansambl Potkozarje', 'Pripremna', 29);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (77, 'Rekreativna grupa Potkozarje', 'Rekreativna', 29);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (78, 'Skolica folklora Potkozarje', 'Skolica folklora', 29);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (79, 'Izvodjacki ansambl Djerdan Laktasi', 'Izvodjacka', 30);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (80, 'Pripremni ansambl Djerdan Laktasi', 'Pripremna', 30);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (81, 'Rekreativna grupa Djerdan Laktasi', 'Rekreativna', 30);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (82, 'Dečiji ansambl Djerdan Laktasi', 'Pocetna', 30);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (83, 'Izvodjacki ansambl Vez Teslic', 'Izvodjacka', 31);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (84, 'Pripremni ansambl Vez Teslic', 'Pripremna', 31);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (85, 'Rekreativna grupa Vez Teslic', 'Rekreativna', 31);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (86, 'Skolica folklora Vez Teslic', 'Skolica folklora', 31);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (87, 'Izvodjacki ansambl Milos Dujic', 'Izvodjacka', 32);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (88, 'Pripremni ansambl Milos Dujic', 'Pripremna', 32);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (89, 'Rekreativna grupa Milos Dujic', 'Rekreativna', 32);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (90, 'Dečiji ansambl Milos Dujic', 'Pocetna', 32);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (91, 'Izvodjacki ansambl Pronija', 'Izvodjacka', 33);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (92, 'Pripremni ansambl Pronija', 'Pripremna', 33);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (93, 'Rekreativna grupa Pronija', 'Rekreativna', 33);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (94, 'Skolica folklora Pronija', 'Skolica folklora', 33);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (95, 'Izvodjacki ansambl Prota Matija Popovic', 'Izvodjacka', 34);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (96, 'Pripremni ansambl Prota Matija Popovic', 'Pripremna', 34);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (97, 'Rekreativna grupa Prota Matija Popovic', 'Rekreativna', 34);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (98, 'Dečiji ansambl Prota Matija Popovic', 'Pocetna', 34);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (99, 'Izvodjacki ansambl Osjecani', 'Izvodjacka', 35);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (100, 'Pripremni ansambl Osjecani', 'Pripremna', 35);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (101, 'Rekreativna grupa Osjecani', 'Rekreativna', 35);
INSERT INTO SEKCIJA (IDS, NAZS, TIPS, KUD_IDKUD) VALUES (102, 'Skolica folklora Osjecani', 'Skolica folklora', 35);